//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02._10._24.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комментарии___
    {
        public int Код { get; set; }
        public Nullable<int> Код_Отеля { get; set; }
        public string Комментарий { get; set; }
        public string Автор { get; set; }
        public Nullable<System.DateTime> Дата_публикации { get; set; }
    
        public virtual Отели Отели { get; set; }
    }
}
