//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02._10._24.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры
    {
        public int id_tour { get; set; }
        public Nullable<int> id_hotel { get; set; }
        public string Название_тура { get; set; }
        public string Страна { get; set; }
        public Nullable<int> Количество_билетов { get; set; }
        public Nullable<double> Цена { get; set; }
        public Nullable<bool> IsActual { get; set; }
        public Nullable<int> Типы_туров { get; set; }
    
        public virtual Отели Отели { get; set; }
        public virtual Типы_туров___ Типы_туров___ { get; set; }
    }
}
